apiVersion: v1
kind: Service
metadata:
  name: flask-app
  namespace: kubernetesns
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30000  # Choose a port in the 30000-32767 range
  type: NodePort

